hospitalDashboard/hospitalDashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hospitalDashboard/users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('', views.homePage, name='homepage'),
    path('register/', views.registerUser, name='register'),
    path('dashboard/', views.userAccount, name='dashboard'),
    path('update-profile/<str:pk>/', views.updateProject, name='update'),
]

# urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hospitalDashboard/users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.
class Profile(models.Model):
    ACCOUNT_USER_TYPE = [
        ("doctor","Doctor"),
        ("patient", "Patient"),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    profile_image = models.ImageField(null=True, blank=True, default="user-default.png")
    account_user_type = models.CharField(max_length=10, choices=ACCOUNT_USER_TYPE)
    address = models.CharField(max_length=200, blank=True, null=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.user.username)

import users.signals

hospitalDashboard/users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)



class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_image','account_user_type', 'address']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

hospitalDashboard/users/views.py
from django.shortcuts import render, redirect, HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from .forms import CustomUserCreationForm, ProfileForm
from django.contrib import messages
from .models import Profile


# Create your views here.
def loginUser(request):
    page = 'login'

    if request.user.is_authenticated:
        return redirect('dashboard')

    if request.method == 'POST':
        username = request.POST['username'].lower()
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Username does not exist')
            return redirect('login')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('dashboard')

        else:
            messages.error(request, 'Username OR password is incorrect')

    return render(request, 'users/login.html')

def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm()
    profile_form = ProfileForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        profile_form = ProfileForm(request.POST, request.FILES)

        if form.is_valid() and profile_form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            # profile = profile_form.save(commit=False)
            # profile.user = user
            # profile.save()
            profile = user.profile
            profile.account_user_type = profile_form.cleaned_data.get('account_user_type')
            profile.address = profile_form.cleaned_data.get('address')
            profile.save()

            login(request, user)
            return HttpResponseRedirect('/dashboard/')
        else:
            return HttpResponse('Failed!')
        
    context = {'page':page, 'form':form, 'profile_form':profile_form}
    return render(request, 'users/signup.html', context)

def logoutUser(request):
    logout(request)
    messages.info(request, 'User was logged out!')
    return redirect('login')

def homePage(request):
    return render(request, 'users/homepage.html')

@login_required(login_url='login')
def userAccount(request):
    profile, created = Profile.objects.get_or_create(user=request.user)
    context = {'user': request.user, 'profile': profile}
    return render(request, 'users/dashboard.html', context)

@login_required(login_url='login')
def updateProject(request, pk):
    user_profile = Profile.objects.get(id=pk)
    form = ProfileForm(instance=user_profile)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('dashboard')

    context = {'form':form}
    return render(request, 'users/update-profile.html', context)

hospitalDashboard/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Navbar</title>
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
</head>
<body>
    <ul class="navbar">
        <!-- Add more menu items as needed -->
        {% if request.path == '/login/' %}
        <li><h2 class="title">Login Page</h2></li>
        {% elif request.path == '/register/' %}
        <li><h2 class="title">Signup Page</h2></li>
        {% elif request.path == '/dashboard/' %}
        <li><h2 class="title">Dashboard</h></li>
        {% endif%}
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'update' profile.id %}">Update Profile</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'homepage' %}">Homepage</a></li>
        {% endif %}
    </ul>
</body>
</html>

hospitalDashboard/users/templates/users/dashboard.html
{% include 'navbar.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
</head>
<body>
    <div class="dashboard-container">
        <h2 class="dashboard-title">Hi, {{ user.first_name }} {{ user.last_name }}</h2>
        <img src="{{ profile.profile_image.url }}" alt="Profile Image" class="profile-img">
        <ul class="dashboard-info">
            <li><p><strong>Username:</strong> {{ user.username }}</p></li>
            <li><p><strong>Email Address:</strong> {{ user.email }}</p></li>
            <li><p><strong>Address:</strong> {{ profile.address }}</p></li>
            <li><p><strong>User Type:</strong> {{ profile.get_account_user_type_display }}</p></li>
        </ul>
    </div>
</body>
</html>

hospitalDashboard/users/templates/users/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
</head>
<body>
    <div class="homepage-container">
        <h1 class="title">Homepage</h1>
        <h1>Welcome To Hospital Dashboard!</h1>
        <div class="homepage-actions">
            <h3 class="action-heading">Already a user?</h3>
            <button><a href="{% url 'login' %}" class="form-button">Login</a></button>
            <h3 class="action-heading">Don't have an account?</h3>
            <button><a href="{% url 'register' %}" class="form-button">Signup</a></button>
        </div>
    </div>
</body>
</html>

hospitalDashboard/users/templates/users/login.html
{% include 'navbar.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
</head>
<body>
    {% if messages %}
        <div class="message-container">
            {% for message in messages %}
                <div class="message">{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}
    <form method="POST" class="form-container">
        {% csrf_token %}
        <h2 class="form-title">Login</h2>
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" class="form-input" required>
        
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" class="form-input" required>
        
        <button type="submit" class="form-button">Login</button>
        <div class="form-footer">
            <span>Don't have an account?</span>
            <a href="{% url 'register' %}" class="form-link">Signup</a>
        </div>
    </form>
</body>
</html>

hospitalDashboard/users/templates/users/signup.html
{% include 'navbar.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
</head>
<body>
    {% block content %}
    <div class="form-container">
        <h2 class="form-title">Signup</h2>
        <form action="" method="POST" enctype="multipart/form-data" class="form">
            {% csrf_token %}
            {% if messages %}
                <div class="message-container">
                    {% for message in messages %}
                        <div class="message">{{ message }}</div>
                    {% endfor %}
                </div>
            {% endif %}
            {{ profile_form.as_p }}
            {{ form.as_p }}
            <button type="submit" class="form-button">Sign Up</button>
            <div class="form-footer">
                <span>Already have an account?</span>
                <a href="{% url 'login' %}" class="form-link">Login</a>
            </div>
        </form>
    </div>
    {% endblock %}
</body>
</html>

hospitalDashboard/users/templates/users/update-profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Profile</title>
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
</head>
<body>
    <div class="form-container">
        <h2 class="form-title">Update Profile</h2>
        <form method="POST" enctype="multipart/form-data" class="form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="form-button">Update Profile</button>
        </form>
    </div>
</body>
</html>